Add UKI support to all modules

diff --git a/modules/amdgpu_unlock b/modules/amdgpu_unlock
--- a/modules/amdgpu_unlock
+++ b/modules/amdgpu_unlock
@@ -6,13 +6,21 @@ status=off
 main() {
     commandFailure="Enabling amdgpu overclocking has failed."
     echo -e "Enabling amdgpu overclocking... \n"
-    if [ $bootloaderChoice == "grub" ]; then
-        sed -i -e 's/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4 amdgpu.ppfeaturemask=0xffffffff/g' /mnt/etc/default/grub || failureCheck
-        chroot /mnt /bin/bash -c "update-grub" || failureCheck
-    elif [ $bootloaderChoice == "efistub" ]; then
-        sed -i -e 's/OPTIONS="loglevel=4/OPTIONS="loglevel=4 amdgpu.ppfeaturemask=0xffffffff/g' /mnt/etc/default/efibootmgr-kernel-hook || failureCheck
-        chroot /mnt /bin/bash -c "xbps-reconfigure -f linux$(find /mnt/boot -name vmlinuz\* | tr -d "/boot/vmlinuz-" | cut -c -3)" || failureCheck
-    fi
+    case $bootloaderChoice in
+        grub)
+             sed -i -e 's/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4/GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4 amdgpu.ppfeaturemask=0xffffffff/g' || failureCheck
+             chroot /mnt /bin/bash -c "update-grub" || failureCheck
+            ;;
+        efistub)
+            sed -i -e 's/OPTIONS="loglevel=4/OPTIONS="loglevel=4 amdgpu.ppfeaturemask=0xffffffff/g' /mnt/etc/default/efibootmgr-kernel-hook || failureCheck
+            chroot /mnt /bin/bash -c "xbps-reconfigure -f linux$(find /mnt/boot -name vmlinuz\* | tr -d "/boot/vmlinuz-" | cut -c -3)" || failureCheck
+            ;;
+        uki)
+            sed -i -e 's/loglevel=4/loglevel=4 amdgpu.ppfeaturemask=0xffffffff/g' /mnt/root/kernelparams || failureCheck
+            chroot /mnt /bin/bash -c 'rm /boot/efi/EFI/boot/bootx64.efi && ukify build --linux="$(find /boot/vmlinuz*)" --initrd="$(find /boot/initramfs*)" --cmdline="$(cat /root/kernelparams)" --output=/boot/efi/EFI/boot/bootx64.efi' || failureCheck
+            ;;
+    esac
+
     echo -e "amdgpu overclocking enabled. \n"
 
     return 0
diff --git a/modules/kernel_lockdown b/modules/kernel_lockdown
--- a/modules/kernel_lockdown
+++ b/modules/kernel_lockdown
@@ -9,22 +9,35 @@ main() {
 
     commandFailure="Enabling kernel lockdown mode has failed."
     if [ "lockdownChoice" == "integrity" ]; then
-            if [ "$bootloaderChoice" == "grub" ]; then
-                sed -i -e 's/GRUB_CMDLINE_DEFAULT="loglevel=4/GRUB_CMDLINE_DEFAULT="loglevel=4 lockdown=integrity/g' /mnt/etc/default/grub || failureCheck
-                chroot /mnt /bin/bash -c "update-grub" || failureCheck
-            elif [ "$bootloaderChoice" == "efistub" ]; then
-                sed -i -e 's/OPTIONS="loglevel=4/OPTIONS="loglevel=4 lockdown=integrity/g' /mnt/etc/default/efibootmgr-kernel-hook || failureCheck
-                chroot /mnt /bin/bash -c "xbps-reconfigure -f linux$(find /mnt/boot -name vmlinuz\* | tr -d "/boot/vmlinuz-" | cut -c -3)" || failureCheck
-            fi
-    
+            case $bootloaderChoice in
+                grub)
+                    sed -i -e 's/GRUB_CMDLINE_DEFAULT="loglevel=4/GRUB_CMDLINE_DEFAULT="loglevel=4 lockdown=integrity/g' /mnt/etc/default/grub || failureCheck
+                    chroot /mnt /bin/bash -c "update-grub" || failureCheck
+                    ;;
+                efistub)
+                    sed -i -e 's/OPTIONS="loglevel=4/OPTIONS="loglevel=4 lockdown=integrity/g' /mnt/etc/default/efibootmgr-kernel-hook || failureCheck
+                    chroot /mnt /bin/bash -c "xbps-reconfigure -f linux$(find /mnt/boot -name vmlinuz\* | tr -d "/boot/vmlinuz-" | cut -c -3)" || failureCheck
+                    ;;
+                uki)
+                    sed -i -e 's/loglevel=4/loglevel=4 lockdown=integrity/g' /mnt/root/kernelparams || failureCheck
+                    chroot /mnt /bin/bash -c 'rm /boot/efi/EFI/boot/bootx64.efi && ukify build --linux="$(find /boot/vmlinuz*)" --initrd="$(find /boot/initramfs*)" --cmdline="$(cat /root/kernelparams)" --output=/boot/efi/EFI/boot/bootx64.efi' || failureCheck
+                    ;;
+            esac
     elif [ "$lockdownChoice" == "confidentiality" ]; then
-            if [ "$bootloaderChoice" == "grub" ]; then
-                sed -i -e 's/GRUB_CMDLINE_DEFAULT="loglevel=4/GRUB_CMDLINE_DEFAULT="loglevel=4 lockdown=confidentiality/g' /mnt/etc/default/grub || failureCheck
-                chroot /mnt /bin/bash -c "update-grub" || failureCheck
-            elif [ "$bootloaderChoice" == "efistub" ]; then
-                sed -i -e 's/OPTIONS="loglevel=4/OPTIONS="loglevel=4 lockdown=confidentiality/g' /mnt/etc/default/efibootmgr-kernel-hook || failureCheck
-                chroot /mnt /bin/bash -c "xbps-reconfigure -f linux$(find /mnt/boot -name vmlinuz\* | tr -d "/boot/vmlinuz-" | cut -c -3)" || failureCheck
-            fi
+            case $bootloaderChoice in
+                grub)
+                    sed -i -e 's/GRUB_CMDLINE_DEFAULT="loglevel=4/GRUB_CMDLINE_DEFAULT="loglevel=4 lockdown=confidentiality/g' /mnt/etc/default/grub || failureCheck
+                    chroot /mnt /bin/bash -c "update-grub" || failureCheck
+                    ;;
+                efistub)
+                    sed -i -e 's/OPTIONS="loglevel=4/OPTIONS="loglevel=4 lockdown=confidentiality/g' /mnt/etc/default/efibootmgr-kernel-hook || failureCheck
+                    chroot /mnt /bin/bash -c "xbps-reconfigure -f linux$(find /mnt/boot -name vmlinuz\* | tr -d "/boot/vmlinuz-" | cut -c -3)" || failureCheck
+                    ;;
+                uki)
+                    sed -i -e 's/loglevel=4/loglevel=4 lockdown=confidentiality/g' /mnt/root/kernelparams || failureCheck
+                    chroot /mnt /bin/bash -c 'rm /boot/efi/EFI/boot/bootx64.efi && ukify build --linux="$(find /boot/vmlinuz*)" --initrd="$(find /boot/initramfs*)" --cmdline="$(cat /root/kernelparams)" --output=/boot/efi/EFI/boot/bootx64.efi' || failureCheck
+                    ;;
+            esac
     fi
 
     return 0
